CREATE TABLE EMPLOYEE(
	EmpNo INT IDENTITY PRIMARY KEY,
	EmpName CHAR(20),
	BirthDay DATE,
	DeptNo INT,
	MgrNo INT NOT NULL,
	StartDate TIMESTAMP,
	Salary MONEY,
	Level INT,
	Status INT,
	Note VARCHAR(200),
);
ALTER TABLE EMPLOYEE
ADD CONSTRAINT CHECK_LEVEL CHECK (Level >=1 AND Level <=7)
GO
ALTER TABLE EMPLOYEE
ADD CONSTRAINT CHECK_STATUS CHECK (Status >=0 AND Status <=2)
GO
CREATE TABLE SKILL(
	SkillNo INT IDENTITY PRIMARY KEY,
	SkillName CHAR(20),
	Note VARCHAR(200)
);
CREATE TABLE DEPARTMENT(
	DeptNo INT PRIMARY KEY,
	DeptName CHAR(20),
	Note VARCHAR(200)
	);
CREATE TABLE EMP_SKILL(
	SkillNo INT ,
	EmpNo INT ,
	SkillLevel INT,
	RegDate DATE,
	Description VARCHAR(200),
	CONSTRAINT EMP_ALL PRIMARY KEY(SkillNo,EmpNo),
	CONSTRAINT EMP_e FOREIGN KEY(SkillNo) REFERENCES SKILL(SkillNo),
	CONSTRAINT emp_k FOREIGN KEY(EmpNo) REFERENCES EMPLOYEE(EmpNo)
	);
ALTER TABLE EMPLOYEE
ADD Email CHAR(20) UNIQUE
ALTER TABLE EMPLOYEE
ADD CONSTRAINT D_TWO
DEFAULT '0' FOR MgrNo;
ALTER TABLE EMPLOYEE
ADD CONSTRAINT D_TW2
DEFAULT '0' FOR Status;

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DeptNo) REFERENCES DEPARTMENT(DeptNo);

ALTER TABLE EMP_SKILL
DROP COLUMN Description;