CREATE DATABASE Fresher_Training_2020
GO
CREATE TABLE Trainee (
	TraineeID INT IDENTITY PRIMARY KEY,
	Full_Name VARCHAR(200),
	Birth_Date DATE,
	Gender BIT,
	ET_IQ INT,
	ET_Gmath INT,
	ET_English INT,
	Training_Class CHAR(10),
	Evaluation_Notes VARCHAR(200)
)
GO
ALTER TABLE Trainee
ADD CONSTRAINT CHECK_ET_IQ CHECK (ET_IQ >= 0 AND ET_IQ <= 20)
GO
ALTER TABLE Trainee
ADD CONSTRAINT CHECK_ET_Gmath CHECK (ET_Gmath >= 0 AND ET_Gmath <= 20)
GO
ALTER TABLE Trainee
ADD CONSTRAINT CHECK_ET_English CHECK (ET_English >= 0 AND ET_English <= 50)
GO

INSERT INTO Trainee
VALUES ('DANH','7/12/1998',1,7,12,39,'NET03','HARDLY,FRIENDLY' )
GO
INSERT INTO Trainee
VALUES ('LAM','3/11/1998',0,8,10,30,'NET01','FRIENDLY,SERIOUS' )
GO
INSERT INTO Trainee
VALUES ('HUY','5/2/1996',1,7,16,43,'NET02','SERIOUS,SMART' )
GO
INSERT INTO Trainee
VALUES ('TRANG','7/12/1998',1,7,12,31,'NET01','SMART,LAZY' )
GO
INSERT INTO Trainee
VALUES ('PHUONG','7/12/1998',1,7,12,3,'NET02','LAZY,MODEST' )
GO
INSERT INTO Trainee
VALUES ('ANH','7/12/1998',1,7,12,42,'NET03','HARDLY,SMART' )
GO
INSERT INTO Trainee
VALUES ('HOA','7/12/1998',1,7,12,49,'NET02','MODEST,SMART' )
GO
INSERT INTO Trainee
VALUES ('NHUNG','4/2/1998',1,7,12,14,'NET01','HARDLY,SMART' )
GO
INSERT INTO Trainee
VALUES ('KAKA','8/12/1998',1,7,12,4,'NET02','FRIENDLY,SMART' )
GO
INSERT INTO Trainee
VALUES ('RONALDO','9/12/1998',1,7,12,9,'NET03','SMART,SERIOUS' )
GO
ALTER TABLE Trainee
ADD Fsoft_Account CHAR(20)
ALTER TABLE Trainee
MODIFY Fsoft_Account CHAR(20) NOT NULL;
ALTER TABLE Trainee
ADD CONSTRAINT UC_Fsoft_Account UNIQUE(Fsoft_Account);
CREATE VIEW  ET_passed AS
SELECT TraineeID,Full_Name,Birth_Date
FROM Trainee
WHERE ET_IQ + ET_Gmath >= 20 AND ET_IQ >= 8 AND ET_Gmath >= 8 AND ET_English >= 18

SELECT TraineeID,Full_Name,Birth_Date
FROM Trainee
WHERE ET_IQ + ET_Gmath >= 20 AND ET_IQ >= 8 AND ET_Gmath >= 8 AND ET_English >= 18
ORDER BY MONTH(Birth_Date)

SELECT TraineeID,Full_Name,Birth_Date,
		YEAR(GETDATE())-YEAR(Birth_Date) AS AGE,
		Gender
FROM Trainee
WHERE LEN(Full_Name) = (SELECT MAX(LEN(Full_Name))FROM Trainee)